# Generated by Django 3.1 on 2020-09-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_visualize'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondParametr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
